"""
LLM extraction runner — the CI entry point that drives the requirements +
architecture agents over meeting transcripts and emits REQ-xxx / ADR drafts.

Closes the gap that the offline minutes pipeline (pipeline.ingest) left open:
minutes were generated for the summer meetings, but the *LLM* agents that
synthesize requirements and architecture decisions were never re-run on that
data. This runner drives them:

    transcript  --transcript_parser (LLM)-->  parsed minutes (decisions, actions…)
                --req_extractor (LLM)------->  categorized requirements  -> requirements/parsed/REQ-xxx.md
                --adr_generator (LLM)------->  architecture decision records -> docs/adr/ADR-*.md

It reuses the real agents' prompts and generation logic (agents/requirements/,
agents/architecture/). The runner plays the role the GitHub/Jira MCP plays in
production: it writes the artifacts to disk and lets CI open a PR, so a human
reviews every generated requirement and ADR before it is baselined (metamodel:
Process -> Artifact -> human Verification).

Idempotent: requirements are de-duplicated by normalized title against what's
already in requirements/parsed/, and new IDs are assigned after the current max
(REQ-013, …). ADRs whose target file already exists are skipped.

Run:
    ANTHROPIC_API_KEY=...  python -m pipeline.extract_from_meetings [--since 2026-05-01]
    python -m pipeline.extract_from_meetings --dry-run          # plumbing only, no LLM / no key
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
TRANSCRIPTS_DIR = PROJECT_ROOT / "transcripts"
REQ_DIR = PROJECT_ROOT / "requirements" / "parsed"
ADR_DIR = PROJECT_ROOT / "docs" / "adr"

CATEGORY_LABELS = {
    "FUNCTIONAL": "Functional Requirement",
    "NON_FUNCTIONAL": "Non-Functional Requirement (Quality Attribute)",
    "USER_GOAL": "User Goal",
    "SOFT_GOAL": "Soft Goal",
    "CONSTRAINT": "Constraint",
}


# ---------------------------------------------------------------------------
# Pure-stdlib helpers (exercised by --dry-run, no LLM / no external deps)
# ---------------------------------------------------------------------------


def date_from_filename(name: str) -> str:
    """GMT20260716-190119_Recording.transcript.vtt -> 2026-07-16."""
    m = re.search(r"GMT(\d{4})(\d{2})(\d{2})", name)
    return f"{m.group(1)}-{m.group(2)}-{m.group(3)}" if m else "unknown"


def _norm(text: str) -> str:
    return re.sub(r"[^a-z0-9 ]", "", (text or "").lower()).strip()


def discover_transcripts(since: str, explicit: list[str] | None) -> list[Path]:
    if explicit:
        return [Path(p) for p in explicit]
    out = []
    for f in sorted(TRANSCRIPTS_DIR.glob("*.transcript.vtt")):
        if date_from_filename(f.name) >= since:
            out.append(f)
    return out


def load_existing_requirements() -> tuple[set[str], int]:
    """Return (normalized existing titles, max REQ number) from disk."""
    titles: set[str] = set()
    max_id = 0
    if not REQ_DIR.exists():
        return titles, max_id
    for f in sorted(REQ_DIR.glob("REQ-*.md")):
        m = re.match(r"REQ-(\d+)", f.name)
        if m:
            max_id = max(max_id, int(m.group(1)))
        header = f.read_text(encoding="utf-8").splitlines()[:1]
        if header:
            # "# REQ-001: Automated product attribute extraction"
            title = re.sub(r"^#\s*REQ-\d+:\s*", "", header[0]).strip()
            if title:
                titles.add(_norm(title))
    return titles, max_id


def format_req_file(req: dict, req_id: str, date: str, meeting_type: str) -> str:
    """Mirror ReqExtractorAgent._format_req_file so dry-run needs no agent import."""
    category = req.get("category", "FUNCTIONAL")
    concerns = req.get("related_concerns") or []
    concerns_md = "\n".join(f"- {c}" for c in concerns) if concerns else "None identified."
    return f"""# {req_id}: {req.get('title', 'Untitled')}

| Field | Value |
|-------|-------|
| **ID** | {req_id} |
| **Category** | {CATEGORY_LABELS.get(category, category)} |
| **Priority** | {req.get('priority', 'P1')} |
| **Date Identified** | {date} |
| **Source Meeting** | {meeting_type} |
| **Source** | {req.get('source_speaker', 'team discussion')} |
| **Status** | draft |

## Requirement Statement

{req.get('statement', '')}

## Rationale

{req.get('rationale', '')}

## Acceptance Criteria

{req.get('acceptance_criteria', 'To be defined.')}

## Related Concerns / Open Questions

{concerns_md}

## Traceability

- Jira Ticket: _pending auto-link_
- Architecture Decision: _pending_
- Test Coverage: _pending_

---
_Auto-generated by req_extractor agent on {date} (CI run, pending human review)_
"""


def adr_filename(date: str, decision_text: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", decision_text[:40].lower()).strip("-")
    return f"ADR-{date}-{slug}.md"


# ---------------------------------------------------------------------------
# LLM paths (agents imported lazily so --dry-run has zero heavy deps)
# ---------------------------------------------------------------------------


def _make_trigger(source: str, date: str, meeting_type: str):
    from agents.base import AgentTrigger

    return AgentTrigger(
        trigger_type="transcript",
        source=source,
        metadata={"date": date, "meeting_type": meeting_type},
    )


def parse_transcript_llm(path: Path, date: str, meeting_type: str) -> dict:
    """Drive the transcript_parser agent's LLM extraction; return parsed minutes."""
    from agents.requirements.transcript_parser import TranscriptParserAgent

    agent = TranscriptParserAgent()
    cleaned = agent._clean_vtt(path.read_text(encoding="utf-8"))
    parsed = agent._parse_with_claude(cleaned, date, meeting_type)
    return parsed or {}


def extract_requirements_llm(parsed: dict, existing_reqs_text: str, date: str) -> list[dict]:
    """Drive the req_extractor agent's LLM synthesis; return requirement dicts."""
    from agents.requirements.req_extractor import ReqExtractorAgent

    agent = ReqExtractorAgent()
    meeting_data = agent._build_meeting_summary(parsed, [])
    if not meeting_data.strip():
        return []
    return agent._extract_with_llm(meeting_data, existing_reqs_text, date) or []


def generate_adr_llm(decision: dict, date: str) -> str:
    """Drive the adr_generator agent's LLM generation; return ADR markdown."""
    from agents.architecture.adr_generator import ADRGeneratorAgent

    return ADRGeneratorAgent()._generate_adr(decision, date)


# ---------------------------------------------------------------------------
# Orchestration
# ---------------------------------------------------------------------------


def run(since: str, files: list[str] | None, max_adrs: int, dry_run: bool) -> dict:
    transcripts = discover_transcripts(since, files)
    existing_titles, max_id = load_existing_requirements()
    REQ_DIR.mkdir(parents=True, exist_ok=True)
    ADR_DIR.mkdir(parents=True, exist_ok=True)

    new_reqs: list[tuple[str, str]] = []   # (req_id, title)
    all_decisions: list[dict] = []
    next_id = max_id + 1

    for path in transcripts:
        date = date_from_filename(path.name)
        meeting_type = "client"

        if dry_run:
            parsed = {
                "decisions": [{"text": f"stub decision for {date}", "context": "dry-run"}],
                "action_items": [{"text": "stub action"}],
                "key_discussion_points": ["stub point about attribute extraction"],
            }
            reqs = [{
                "title": f"Stub requirement from {date}",
                "statement": "The system shall (dry-run placeholder).",
                "category": "FUNCTIONAL", "priority": "P2",
                "rationale": "dry-run", "acceptance_criteria": "n/a",
                "source_speaker": "dry-run", "related_concerns": [],
            }]
        else:
            parsed = parse_transcript_llm(path, date, meeting_type)
            existing_text = "\n".join(f"- {t}" for t in sorted(existing_titles)) or "(none yet)"
            reqs = extract_requirements_llm(parsed, existing_text, date)

        for d in parsed.get("decisions", []) or []:
            if isinstance(d, dict) and d.get("text"):
                all_decisions.append({**d, "_date": date})

        for req in reqs:
            key = _norm(req.get("title", ""))
            if not key or key in existing_titles:
                continue  # dedup vs disk + earlier this run
            req_id = f"REQ-{next_id:03d}"
            next_id += 1
            existing_titles.add(key)
            content = format_req_file(req, req_id, date, meeting_type)
            (REQ_DIR / f"{req_id}.md").write_text(content, encoding="utf-8")
            new_reqs.append((req_id, req.get("title", "")))

    # ADRs — dedup decisions by text, cap total to bound cost
    new_adrs: list[str] = []
    seen_dec: set[str] = set()
    for d in all_decisions:
        if len(new_adrs) >= max_adrs:
            break
        k = _norm(d.get("text", ""))[:80]
        if not k or k in seen_dec:
            continue
        seen_dec.add(k)
        fname = adr_filename(d["_date"], d.get("text", "untitled"))
        target = ADR_DIR / fname
        if target.exists():
            continue
        content = ("# ADR (dry-run placeholder)\n\n## Status\nProposed\n"
                   if dry_run else generate_adr_llm(d, d["_date"]))
        target.write_text(content, encoding="utf-8")
        new_adrs.append(fname)

    return {
        "transcripts": len(transcripts),
        "new_requirements": new_reqs,
        "new_adrs": new_adrs,
    }


def write_summary(result: dict, path: Path | None) -> str:
    lines = ["## Requirements & ADR extraction", ""]
    lines.append(f"Drove the requirements + architecture agents over "
                 f"**{result['transcripts']}** meeting transcript(s).")
    lines.append("")
    reqs = result["new_requirements"]
    if reqs:
        lines.append(f"**{len(reqs)} new requirement(s)** (`requirements/parsed/`):")
        lines += [f"- `{rid}` — {title}" for rid, title in reqs]
    else:
        lines.append("No new requirements (all deduped against existing).")
    lines.append("")
    adrs = result["new_adrs"]
    if adrs:
        lines.append(f"**{len(adrs)} new ADR draft(s)** (`docs/adr/`):")
        lines += [f"- `{a}`" for a in adrs]
    else:
        lines.append("No new ADR drafts.")
    lines += [
        "",
        "**These are agent-generated drafts pending human review.** Check each "
        "requirement's statement/category and each ADR's decision + consequences "
        "before merging — merging this PR is the human approval step.",
    ]
    text = "\n".join(lines)
    if path:
        path.write_text(text, encoding="utf-8")
    return text


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--since", default="2026-05-01",
                        help="Only process transcripts dated on/after this (YYYY-MM-DD).")
    parser.add_argument("--files", nargs="*", default=None,
                        help="Explicit transcript paths (overrides --since).")
    parser.add_argument("--max-adrs", type=int, default=6, help="Cap ADRs generated per run.")
    parser.add_argument("--dry-run", action="store_true",
                        help="Exercise plumbing without any LLM call (no API key needed).")
    parser.add_argument("--summary-file", type=Path, default=None,
                        help="Write the markdown run summary here (for the PR body).")
    args = parser.parse_args()

    result = run(args.since, args.files, args.max_adrs, args.dry_run)
    write_summary(result, args.summary_file)
    print(f"transcripts: {result['transcripts']} | "
          f"new requirements: {len(result['new_requirements'])} | "
          f"new ADRs: {len(result['new_adrs'])}"
          + (" (dry-run)" if args.dry_run else ""), file=sys.stderr)


if __name__ == "__main__":
    main()
