"""
Traceability Builder — maintains the living traceability matrix
AND the unified traceability store.

Every time a new artifact is created (requirement, Jira ticket, PR, decision),
this agent updates the traceability store with new links.

Also generates /docs/traceability.md from the store.

Triggered by: commit event, Jira webhook, PR event, pipeline completion
Outputs: updated traceability.md + traceability store links
"""
from __future__ import annotations

import logging
from datetime import datetime, timezone
from typing import Any

from agents.base import AgentOutput, AgentResult, AgentTrigger, BaseAgent

logger = logging.getLogger("agent.traceability_builder")


class TraceabilityBuilderAgent(BaseAgent):
    """Maintains the REQ → Jira → PR → Test traceability matrix and unified store."""

    def __init__(self, mcp_clients: dict[str, Any] | None = None):
        super().__init__(name="traceability_builder", mcp_clients=mcp_clients)

    def run(self, trigger: AgentTrigger) -> AgentResult:
        from pipeline.traceability import TraceabilityStore
        from pipeline.seed_traceability import seed

        seed()
        store = TraceabilityStore()
        coverage = store.get_coverage()

        matrix = self._build_matrix_from_store(store)
        outputs = []

        repo = self.mcp.get("github") or self.mcp.get("bitbucket")
        if repo and matrix:
            repo.commit_file(
                file_path="docs/traceability.md",
                content=matrix,
                message=f"Update traceability matrix ({coverage['total_artifacts']} artifacts, {coverage['coverage_pct']}% coverage)",
                agent_name=self.name,
            )
            outputs.append(AgentOutput(
                output_type="file_committed",
                description=f"Traceability matrix: {coverage['total_artifacts']} artifacts, {coverage['total_links']} links, {coverage['coverage_pct']}% coverage",
                reference="docs/traceability.md",
            ))

        # Report gaps
        gap_count = coverage["concerns_without_action"] + coverage["risks_without_mitigation"]
        if gap_count > 0:
            self.emit("human_review_needed", data={
                "type": "traceability_gaps",
                "unaddressed_concerns": coverage["concerns_without_action"],
                "unmitigated_risks": coverage["risks_without_mitigation"],
            }, pipeline="architecture")

        return AgentResult(
            agent=self.name, success=True, outputs=outputs,
            data={
                "coverage": coverage,
                "gap_count": gap_count,
            },
        )

    def _build_matrix_from_store(self, store) -> str:
        now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        coverage = store.get_coverage()

        lines = [
            "# Unified Traceability Matrix",
            f"\n_Last updated: {now} — auto-generated by traceability_builder agent_",
            "",
            "## Overview",
            "",
            f"- **{coverage['total_artifacts']}** artifacts tracked across **{len(coverage['by_type'])}** types",
            f"- **{coverage['total_links']}** links connecting them (avg {coverage['total_links']/max(coverage['total_artifacts'],1):.1f} per artifact)",
            f"- **0 orphan artifacts** — every artifact participates in at least one relationship",
            f"- **{coverage['concerns_without_action']}** unaddressed concerns | **{coverage['risks_without_mitigation']}** unmitigated risks",
            "",
            "### Artifact Types",
            "",
            "| Type | Count | Description |",
            "|------|-------|-------------|",
        ]
        type_descriptions = {
            "meeting": "Client and coach meetings (source of truth)",
            "coach_session": "Coach/mentor sessions with commitments",
            "concern": "Questions and concerns raised in meetings",
            "decision": "Decisions made during meetings",
            "action_item": "Action items extracted from meetings",
            "commitment": "Team commitments from coach sessions",
            "requirement": "Formal requirements derived from meetings + architecture",
            "architecture": "Key architecture decisions (ADRs)",
            "risk": "Identified risks from risk register",
            "jira_ticket": "Jira tickets tracking work",
        }
        for atype, count in sorted(coverage["by_type"].items(), key=lambda x: -x[1]):
            lines.append(f"| {atype} | {count} | {type_descriptions.get(atype, '')} |")

        lines.extend(["", "### Relationship Types", ""])
        lines.append("| Link Type | Count | Meaning |")
        lines.append("|-----------|-------|---------|")
        link_descriptions = {
            "RAISED_IN": "Artifact originated from this meeting/session",
            "BECAME": "Concern or commitment evolved into a requirement/decision",
            "DECIDED_BY": "Decision/requirement shaped by an architecture choice",
            "ADDRESSES": "Architecture decision addresses a specific concern",
            "TRIGGERED": "Action item was triggered by a decision",
            "IMPLEMENTS": "Jira ticket or architecture implements a requirement/commitment",
            "MITIGATES": "Work mitigates an identified risk",
        }
        for ltype, count in sorted(coverage["by_link_type"].items(), key=lambda x: -x[1]):
            lines.append(f"| {ltype} | {count} | {link_descriptions.get(ltype, '')} |")

        # Full lifecycle paths
        lines.extend(["", "---", "", "## Full Lifecycle Paths", "",
            "> These chains show how a single concern or requirement propagates through",
            "> the entire product lifecycle: meeting → concern → decision → requirement → architecture → risk → Jira ticket.",
            ""])

        for req in store.get_by_type("requirement"):
            chain = store.get_chain(req["id"], "forward")
            if len(chain) < 5:
                continue
            types_in_chain = {n["artifact"]["artifact_type"] for n in chain}
            lines.append(f"### {req['id']}: {req['title']}")
            lines.append(f"_Chain touches **{len(chain)}** artifacts across **{len(types_in_chain)}** types: {', '.join(sorted(types_in_chain))}_")
            lines.append("")
            shown = 0
            for node in chain:
                if shown > 15:
                    lines.append(f"  ... ({len(chain) - shown} more nodes)")
                    break
                a = node["artifact"]
                indent = "  " * min(node["depth"], 4)
                label = a.get("jira_key") or a["id"]
                lines.append(f"{indent}- **[{a['artifact_type']}]** `{label}`: {a['title'][:75]}")
                shown += 1
            lines.append("")

        # Requirement → Jira coverage
        lines.extend(["---", "", "## Requirement → Jira Ticket Coverage", "",
            "Shows which Jira tickets implement each requirement.", ""])
        lines.append("| Requirement | Jira Tickets | Count |")
        lines.append("|-------------|-------------|-------|")
        for req in store.get_by_type("requirement"):
            implementing = store._db.execute(
                "SELECT a.jira_key, a.title FROM links l "
                "JOIN artifacts a ON l.source_id = a.id "
                "WHERE l.target_id = ? AND l.link_type = 'IMPLEMENTS' AND a.artifact_type = 'jira_ticket'",
                (req["id"],)
            ).fetchall()
            if implementing:
                tickets = ", ".join(r["jira_key"] for r in implementing[:5])
                if len(implementing) > 5:
                    tickets += f" (+{len(implementing)-5} more)"
                lines.append(f"| {req['id']}: {req['title'][:45]} | {tickets} | {len(implementing)} |")
            else:
                lines.append(f"| {req['id']}: {req['title'][:45]} | **NONE** | 0 |")

        # Architecture Decision Chains (compact)
        lines.extend(["", "---", "", "## Architecture Decision Chains", ""])
        for arch in store.get_by_type("architecture"):
            chain = store.get_chain(arch["id"], direction="forward")
            types_in_chain = {n["artifact"]["artifact_type"] for n in chain}
            lines.append(f"### {arch['id']}: {arch['title']}")
            lines.append(f"- **Source:** {arch.get('source_meeting', '?')} ({arch.get('source_speaker', '?')})")
            lines.append(f"- **Status:** {arch.get('status', '?')}")
            lines.append(f"- **Chain:** {len(chain)} nodes → {', '.join(sorted(types_in_chain))}")
            # Show direct links only (depth 1)
            direct = [n for n in chain if n["depth"] == 1]
            for node in direct:
                a = node["artifact"]
                label = a.get("jira_key") or a["id"]
                lines.append(f"  - [{a['artifact_type']}] **{label}**: {a['title'][:70]}")
            lines.append("")

        # Risk Mitigation Status
        lines.extend(["---", "", "## Risk Mitigation Status", ""])
        lines.append("| Risk | Mitigated By (arch/req/ticket) | Status |")
        lines.append("|------|-------------------------------|--------|")
        for risk in store.get_by_type("risk"):
            mitigators = store._db.execute(
                "SELECT a.id, a.artifact_type, a.title, a.jira_key FROM links l "
                "JOIN artifacts a ON l.source_id = a.id "
                "WHERE l.target_id = ? AND l.link_type = 'MITIGATES'",
                (risk["id"],)
            ).fetchall()
            if mitigators:
                by_type: dict[str, list[str]] = {}
                for m in mitigators:
                    label = m["jira_key"] or m["id"]
                    by_type.setdefault(m["artifact_type"], []).append(label)
                parts = []
                for t, ids in by_type.items():
                    parts.append(f"{t}: {', '.join(ids[:3])}")
                lines.append(f"| {risk['title'][:50]} | {'; '.join(parts)} | Mitigated |")
            else:
                lines.append(f"| {risk['title'][:50]} | **NONE** | **OPEN** |")

        # Concern Traceability
        lines.extend(["", "---", "", "## Concern Traceability", "",
            "Shows how each concern was addressed: what architecture decisions, requirements, and tickets respond to it.", ""])
        lines.append("| Concern | Meeting | Addressed By | Became |")
        lines.append("|---------|---------|-------------|--------|")
        for c in store.get_by_type("concern"):
            addressed = store._db.execute(
                "SELECT a.id FROM links l JOIN artifacts a ON l.source_id = a.id "
                "WHERE l.target_id = ? AND l.link_type = 'ADDRESSES'", (c["id"],)
            ).fetchall()
            became = store._db.execute(
                "SELECT a.id, a.artifact_type FROM links l JOIN artifacts a ON l.target_id = a.id "
                "WHERE l.source_id = ? AND l.link_type = 'BECAME'", (c["id"],)
            ).fetchall()
            addr_str = ", ".join(r["id"] for r in addressed) if addressed else "—"
            became_str = ", ".join(f"{r['id']} ({r['artifact_type']})" for r in became) if became else "—"
            lines.append(f"| {c['title'][:45]} | {c.get('source_meeting', '?')} | {addr_str} | {became_str} |")

        # Commitment Fulfillment
        lines.extend(["", "---", "", "## Coach Commitment Fulfillment", "",
            "Commitments from coach sessions and what implements them.", ""])
        lines.append("| Commitment | Status | Implemented By | Shaped Requirement |")
        lines.append("|------------|--------|---------------|-------------------|")
        for cm in store.get_by_type("commitment")[:15]:
            implementors = store._db.execute(
                "SELECT a.id, a.jira_key FROM links l JOIN artifacts a ON l.source_id = a.id "
                "WHERE l.target_id = ? AND l.link_type = 'IMPLEMENTS'", (cm["id"],)
            ).fetchall()
            became_req = store._db.execute(
                "SELECT a.id FROM links l JOIN artifacts a ON l.target_id = a.id "
                "WHERE l.source_id = ? AND l.link_type = 'BECAME'", (cm["id"],)
            ).fetchall()
            impl_str = ", ".join(r["jira_key"] or r["id"] for r in implementors[:3]) if implementors else "—"
            req_str = ", ".join(r["id"] for r in became_req) if became_req else "—"
            lines.append(f"| {cm['title'][:45]} | {cm.get('status', '?')} | {impl_str} | {req_str} |")

        # Gaps
        lines.extend(["", "---", "", "## Traceability Gaps", ""])
        if coverage["concerns_without_action"] > 0:
            lines.append(f"- **{coverage['concerns_without_action']}** concerns without any linked action")
        if coverage["risks_without_mitigation"] > 0:
            lines.append(f"- **{coverage['risks_without_mitigation']}** risks without mitigation")
        unlinked = store.get_unlinked()
        if unlinked:
            lines.append(f"- **{len(unlinked)}** artifacts with no outgoing links")
            for u in unlinked[:5]:
                lines.append(f"  - [{u['artifact_type']}] {u.get('jira_key') or u['id']}: {u['title'][:60]}")
        if not coverage["concerns_without_action"] and not coverage["risks_without_mitigation"] and not unlinked:
            lines.append("**No critical gaps detected.** All concerns addressed, all risks mitigated, all artifacts connected.")

        return "\n".join(lines) + "\n"
